spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_db
    username: board_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 61fff6f5e1450666e9ab1a99e0fd69ff
            redirect-uri: http://13.124.67.168:8080
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
